### ISSUE TITLE
新番区地址解析和视频的真实地址问题

### ISSUE THREAD

**Issue by madlight-du** [Meloduet/Wpf-BilibiliVideoFetcher#4]
1、新番区链接依然解析不能
http://bangumi.bilibili.com/anime/v/96688
以这个视频为例，创建任务毫无反应。

2、解析出来的下载地址有问题
![image](https://cloud.githubusercontent.com/assets/3970620/19060423/b2b5a1a0-8a1a-11e6-961c-196756e0a549.png)
以这个视频为例，解析出来的真实下载地址是这个，是暴走漫画的一个视频
http://14.215.9.36/ws.acgvideo.com/6/bf/6456542-1hd.mp4?wsTime=1475575657&wsSecret2=0988d4831005ccc662a5ad09354dc87e&oi=2067479167&rate=400&wshc_tag=0&wsts_tag=57f30ef5&wsid_tag=77890245&wsiphost=ipdbm

系统环境win8.1 X64，下载工具IDM

**Comment by EwigMidori** [comment]
好的我尽快修复

**Comment by EwigMidori** [comment]
已修复
